#PBS -N Blastp
#PBS -l nodes=1:ppn=2
#PBS -l mem=2gb
#PBS -l walltime=12:00:00
#PBS -q YOUR_QUEUE     
#PBS -A YOUR_ACCOUNT
#PBS -o 02b_BlastP.out
#PBS -e 02b_BlastP.err

# Change to working directory
cd $PBS_O_WORKDIR

# Set python script directory
scripts=/Path/to/GitHub/repo/02_Python

# Load Modules Needed
module load blast-plus/2.10.1

# Make Blast DB
if [ ! -s ${ref}.pdb ]
  then
      	makeblastdb -dbtype prot -in $ref
fi

# Make output directory
if [ ! -d 02b_filter ]; then mkdir 02b_filter; fi

# Run Blast
blastp -num_threads 2 -max_target_seqs 10 \
-db ${ref} -query ${qry} -out ${out}.blast  -subject_besthit -outfmt \
'6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qlen slen'

# Filter Blast and plot hists
#	1) Remove matches >= 98% identity to verified sequences
#	2) Removes matches <= 30% identity to verified sequences
#	3) Remove matches with <= 50% sequence alignment (alignment length / query sequence length).

python ${scripts}/02b_Blastp_filter_hist.py -i ${out}.blast -o ${out}

# Get Blast Filtered Fasta Sequence
python ${scripts}/02c_Get_Fasta_from_Filtered_Blast.py -b ${out}.fltrdBstHts.blst -q ${qry} -o ${out}_blast_fltrd.fasta
python ${scripts}/02c_Get_Fasta_from_Filtered_Blast.py -b 02b_filter/${out}_pID100.blst -q ${qry} -o 02b_filter/${out}_pID100.fa

## Run Log ##
## qsub -v ref=OG.faa,qry=derep_representatives.faa,out=out.blast /Path/to/GitHub/repo/01a_PBS/00b_BlastP.pbs

