#PBS -N ClustalO
#PBS -l nodes=1:ppn=12
#PBS -l mem=10gb
#PBS -l walltime=4:00:00
#PBS -q YOUR_QUEUE
#PBS -A YOUR_ACCOUNT
#PBS -o 02d_ClustalO.out
#PBS -e 02d_ClustalO.err

# This script builds the gene clusters
cd $PBS_O_WORKDIR

# Make output directory
if [ ! -d 03_ROCkIn_Results ]; then mkdir 03_ROCkIn_Results; fi

# Load your servers clustalo module or clustalo must be available in your PATH
module load clustal-omega # change this for your server

if [ ! -s ${verified}.aln ]
  then
        n1=`basename ${verified}`
        clustalo -i $verified -o 03_ROCkIn_Results/03a_${n1}.aln --threads 12
fi

n2=`basename ${newseqs} | cut -d_ -f2-`
clustalo -i $newseqs -o 03_ROCkIn_Results/03a_${n2}.aln --profile1 03_ROCkIn_Results/03a_${n1}.aln --threads 12

## Run Log:
## qsub -v verified=,newseqs= /Path/to/GitHub/repo/01a_PBS/02d_seq_alignment.pbs

